### ISSUE TITLE
Following instructions in README and get error

### ISSUE THREAD

**Issue by mocheng** [reactopt/reactopt#62]
**Repo Steps:**
1. create an react v16 app with `create-react-app` v1.4.1.
2. run `npm install --save-dev reactopt` in the created project.
3. add `"reactopt": "node node_modules/reactopt/main.js"` to `package.json`.
4. run `npm run reactopt localhost:3000`

**Actual Results:**
It failed with below error:

```
puppeteer.launch({headless: false}).then(async browser => {
                                         ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

BTW, the README states that below code should be in main component file.
```
import React from 'react'
 
if (process.env.NODE_ENV !== 'production') {
    import { reactopt } from 'reactopt';
    reactopt(React);
}
```
But, import statement should NOT be in conditional branch IMHO. I suppose it would fail even we fix the async error problem.

**Comment by itspamlam** [comment]
@mocheng Thanks for trying our app out!

It seems like your main issue is with async/await which should be supported in Node 7.6+. That wasn't listed in our dependencies but I'll update that. Could you check on that and let us know if you're still having issues?

Also, I corrected the README instructions to a require statement instead. Thanks for pointing that out!

**Comment by enapupe** [comment]
While we are at this dependency subject, what is the minor react version supported? It would be a great addition to the readme file. thanks

**Comment by mocheng** [comment]
@itspamlam I was running on Node v6.9.2. I'll try on latest Node v8.

**Comment by kyriejoshua** [comment]
@itspamlam I have the same problem even if i ran on Node v7.6.0 or Node v8.0.0.

**Comment by itspamlam** [comment]
@enapupe Thanks for bring this up. We're currently gathering feedback from users on what to update, including content for the readme file. I'll definitely pass this along.
