### ISSUE TITLE
Logo in terminal looks strange when a user has a color scheme

### ISSUE THREAD

**Issue by lol-russo** [reactopt/reactopt#70]
Hi there! Awesome work, thank you! I realise this is design feedback rather than code feedback, and probably very low priority in the big scheme of things — but I think this would look a lot nicer for a lot of users if the black background was removed.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/19835679/33534041-26215480-d8f9-11e7-9a29-516c49354a68.png">

**Comment by szmoon** [comment]
Hi! We took the background away and added a border around instead (to account for white backgrounds). Thank you for the feedback, we appreciate it. :)

![cli](https://user-images.githubusercontent.com/5179244/33731953-a6d613bc-db39-11e7-9e45-1e201f3a6c74.png)

**Comment by jacklorusso** [comment]
Looks so much better! Nice work 🙌
